### PR TITLE
Externalize guide content and french translation

### PR DESCRIPTION
**Pull request by BenjaminLeSire**
Hi,

This pull request moves all text in ModGuidePages.java to the lang file, so as to allow translation.

### CODE REVIEW

**Comment by BenjaminLeSire** [comment]
Welp I also added a basic french translation to this pull request.

**Comment by Bartz24** [comment]
First, does the guide work in french?

If so, I'll merge but change a few things though.

I notice you're missing the pages for the plugins too, but you can make the translations after I merge this and change the method for adding pages to keep it simpler.

Keep me updated with new translations etc, as I'm going to change one of the pages soon, along with new pages added.

Thanks, this makes things simpler and allows for translation :D
And thanks for the french translation too :D

**Comment by BenjaminLeSire** [comment]
Yes, the guide works very well, and I suppose it will be the same for most languages. There are a few things that will need to be changed though, for example, the way the words are put together in english ("dirty emerald") is not necessarily the same in another language. And there's also some hardcoded text here and there, but as you say, it can wait after this PR is merged.

Thanks for your quick answer :).

**Comment by Bartz24** [comment]
Guess I'll change the way naming is handled :(
Harder for me, easier for translators though.

I'll merge it later today.

**Comment by BenjaminLeSire** [comment]
Internationalization is always a pain, sadly :).

**Comment by Bartz24** [comment]
After I make it simpler and change a guide page, I'll ask you to translate the ones you missed and the one I'm changing.  Look at the changes for the .lang file for en to see after that commit is up. And then put the translations in the French Translations issue for me :D

**Comment by BenjaminLeSire** [comment]
Sure, glad to! If I can be of any help for anything else, feel free to ask.

**Comment by Bartz24** [comment]
Just changed the dirty lang stuff too, so you can do that now :D

**Pull request merged**
